### PR TITLE
fix #28

### LINKED ISSUE #28: differentiate org-level-3 and org-level-4
right now org-level-3 and org-level-4 have the same colouring. consider using a different color for each one in order to increase readability.

screen shot 2016-11-23 at 23 52 26

### PR DESCRIPTION
**Pull request by ninrod**
@NicolasPetton this should fix #28

can you check if the chosen colors are adequate?

thanks.

screen shot 2016-11-27 at 01 40 02

### CODE REVIEW

**Comment by NicolasPetton** [comment]
Thanks @ninrod! I'd keep the red for error and warnings though, could you change it?

**Comment by NicolasPetton** [comment]
@ninrod also, the red bold is used for TODO items in org-mode, so that's another reason to avoid it in headings.

**Comment by ninrod** [comment]
@NicolasPetton, ok! I've swaped the colors. could you review?

**Comment by NicolasPetton** [comment]
Thanks. I think I'd like to keep the purple as 2nd level headings though.

Finding 8 colors for heading is going to be quite hard, what about cycling 4 colors? (That's what some other themes like Solarized are doing IIRC).  I'd go with something like blue, purple, peach & green-light. What do you think?

**Comment by ninrod** [comment]
Yes! It was indeed very hard to find those colors. So blue, purple, peach and green-light it is. let me prepare a commit.

**Comment by ninrod** [comment]
@NicolasPetton, I found that the sequence `(blue purple green orange)` has more constrast than (blue, purple, peach and green-light). Here are 2 screenshots:

ninrodstake

nicolas

what do you decide?

**Comment by NicolasPetton** [comment]
@ninrod the face should be bold, but in your screenshots it's not (or maybe it's a very lightweight bold font?). With bold fonts, the orange color has too much contrasts IMO and attracts a lot of attention, so I would stick to peach + green-light.

**Comment by ninrod** [comment]
hum, interesting. I'm using the (awesome) [Monoid](https://github.com/larsenwork/monoid) font. I'll try with monaco.

Ok, so peach + green-light. I should be able to prepare a commit later today.

**Comment by ninrod** [comment]
Ok, how about know?

**Comment by NicolasPetton** [comment]
Looks, great! Thanks :)

**Comment by bastibl** [comment]
AFAIS, this commit doesn't show up in the history and its changes are not applied.

Did you accidentally --force push?

**Comment by ninrod** [comment]
@NicolasPetton, @bastibl is right. Seems that this mr got lost somewhere. The changes are [not](https://github.com/NicolasPetton/zerodark-theme/blob/master/zerodark-theme.el#L471-L478) in. 

maybe you could cherry pick the changes from my fork: ninrod/zerodark-theme@ea7d3a7c88f65ccc6ca0e07e1a2e52e20115d7d7

**Pull request merged**
