### PR TITLE
Theme font-latex-bold-face and font-latex-italic-face

### PR DESCRIPTION
**Pull request by justbur**

### CODE REVIEW

**Comment by justbur** [comment]
The default foreground for these faces was OliveDrab for me.

**Comment by DamienCassou** [comment]
Could you please add a before/after screenshot?

**Comment by justbur** [comment]
Sure, 

Before
screen shot 2018-01-31 at 2 25 34 pm

After
screen shot 2018-01-31 at 2 26 23 pm

I put a string in the second one to show that I'm just reusing that color.

**Comment by NicolasPetton** [comment]
Thanks!

**Pull request merged**
